use app;
SELECT * FROM playstore_apps_clean_final;

#1. Which apps have the highest rating in the given available dataset?

select app,category,rating from playstore_apps_clean_final where rating = (select max(rating) from playstore_apps_clean_final);

#2. What are the number of installs and reviews for the above apps? Return the apps with the highest reviews to the top.

select app,category,rating,installs,reviews from playstore_apps_clean_final where rating = (select max(rating) from playstore_apps_clean_final)
order by reviews desc;

#3. Which app has the highest number of reviews? Also, mention the number of reviews and category of the app

select app,category,reviews from playstore_apps_clean_final order by reviews desc limit 1;

#4. What is the total amount of revenue generated by the google play store by hosting apps? 
#   (Whenever a user buys apps  from the google play store, the amount is considered in the revenue)

select sum(price) from playstore_apps_clean_final;

#5. Which Category of google play store apps has the highest number of installs? also, find out the total number of installs for that particular category.

select distinct(category),app,installs from  playstore_apps_clean_final order by installs desc limit 1;

#6. Which Genre has the most number of published apps?

select genres,count(genres) from playstore_apps_clean_final group by genres;
select genres,count(genres) from playstore_apps_clean_final where genres = 'tools';

#7. Provide the list of all games ordered in such a way that the game that has the highest number of installs is displayed on the top
# (to avoid duplicate results use distinct)

select distinct(app),category,installs from playstore_apps_clean_final where category='game' order by category,installs desc;

#8. Provide the list of apps that can work on android version 4.0.3 and UP.

select distinct(app),androidver from playstore_apps_clean_final where androidver = '4.0.3 and up';

#9. How many apps from the given data set are free? Also, provide the number of paid apps.

select type,count(type) from playstore_apps_clean_final where type = 'free';
select type,count(type) from playstore_apps_clean_final where type = 'paid';


#10. Which is the best dating app? (Best dating app is the one having the highest number of Reviews)

select * from playstore_apps_clean_final;
select app,category,max(reviews) from playstore_apps_clean_final where category = 'dating';

#11. Get the number of reviews having positive sentiment and number of reviews having negative sentiment for the app 10 best foods for you and compare them.

select * from playstore_reviews_final;
select count(*) from playstore_reviews_final;
select app,sentiment,count(sentiment) from playstore_reviews_final where sentiment = 'negative' and app = '10 Best Foods for You';
select app,sentiment,count(sentiment) from playstore_reviews_final where sentiment = 'positive' and app = '10 Best Foods for You';

#12. Which comments of ASUS SuperNote have sentiment polarity and sentiment subjectivity both as 1?

select app,translatedreview,sentimentpolarity,sentimentsubjectivity from playstore_reviews_final 
where app = 'asus supernote' 
and sentimentpolarity = 1
 and sentimentsubjectivity = 1;

#13. Get all the neutral sentiment reviews for the app Abs Training-Burn belly fat 

select * from playstore_reviews_final;
select app,translatedreview,sentiment from playstore_reviews_final where app='Abs Training-Burn belly fat' and sentiment = 'neutral';

#14. Extract all negative sentiment reviews for Adobe Acrobat Reader with their sentiment polarity and sentiment subjectivity

select * from playstore_reviews_final where app = 'Adobe Acrobat Reader' and sentiment = 'negative';

